# Generated by Django 4.2.20 on 2025-04-24 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kabupaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kabupaten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kecamatans', to='users.kabupaten')),
            ],
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kelurahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kelurahans', to='users.kecamatan')),
            ],
        ),
        migrations.AddField(
            model_name='kabupaten',
            name='provinsi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kabupatens', to='users.provinsi'),
        ),
        migrations.CreateModel(
            name='Alamat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_alamat', models.CharField(max_length=255)),
                ('kode_pos', models.CharField(blank=True, max_length=10, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('kabupaten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.kabupaten')),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.kecamatan')),
                ('kelurahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.kelurahan')),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.provinsi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alamats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
