# Generated by Django 4.2.20 on 2025-05-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_kabupaten_kecamatan_provinsi_kelurahan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alamat',
            name='nama_alamat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
