# Generated by Django 4.2.20 on 2025-04-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='design',
            name='slug',
            field=models.SlugField(default='-', max_length=200, unique=True),
        ),
    ]
