# Generated by Django 4.2.20 on 2025-04-15 23:04

import designs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_design_description_design_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='design_aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.ImageField(upload_to=designs.models.design_color_image_path),
        ),
    ]
