# Generated by Django 4.2.20 on 2025-04-07 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designs', '0001_initial'),
        ('cart', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designs.design'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcolor'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcolordetail'),
        ),
    ]
