# Generated by Django 4.2.20 on 2025-05-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_remove_order_expedition_and_more'),
    ]

    operations = [
        
    ]
