# Generated by Django 4.2.20 on 2025-05-01 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_kabupaten_kecamatan_provinsi_kelurahan_and_more'),
        ('products', '0005_alter_productcolor_image'),
        ('orders', '0004_remove_order_alamat_remove_order_diskon_persen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.productcolor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.productcolordetail'),
            preserve_default=False,
        ),
    ]
