# Generated by Django 4.2.20 on 2025-05-01 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_kabupaten_kecamatan_provinsi_kelurahan_and_more'),
        ('orders', '0005_delete_expedition_order_alamat_order_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expedition',
        ),
        migrations.AddField(
            model_name='order',
            name='alamat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.alamat'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='total_harga_barang',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
