# Generated by Django 4.2.20 on 2025-05-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_delete_expedition_order_alamat_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='diskon_persen',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
