# Generated by Django 4.2.20 on 2025-05-06 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_diskon_rupiah_order_ongkos_kirim_order_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ekspedisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EkspedisiDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ekspedisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='orders.ekspedisi')),
            ],
        ),
    ]
