# Generated by Django 4.2.20 on 2025-05-13 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_ekspedisidetail_default_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ekspedisi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.ekspedisi'),
        ),
        migrations.AddField(
            model_name='order',
            name='ekspedisi_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.ekspedisidetail'),
        ),
    ]
