# Generated by Django 4.2.20 on 2025-04-07 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcolordetail',
            old_name='color',
            new_name='productcolor',
        ),
    ]
