# Generated by Django 4.2.20 on 2025-04-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_color_remove_productcolor_color_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='default_color',
        ),
        migrations.AddField(
            model_name='productcolor',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
