# Generated by Django 4.2.20 on 2025-04-15 09:42

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_default_color_productcolor_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='image',
            field=models.ImageField(upload_to=products.models.product_color_image_path),
        ),
    ]
